name: Build and Release Lucent PHAR
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - 'build.php'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: testpassword
          MYSQL_DATABASE: test_database
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: phar, mysqli, pdo_mysql
          tools: composer:v2
          coverage: xdebug
          ini-values: phar.readonly=0

      - name: Install PHPUnit
        run: |
          composer require --dev phpunit/phpunit
          composer dump-autoload

      - name: Create temp directories
        run: |
          mkdir -p temp_install/packages
          mkdir -p temp_install/App/Commands
          mkdir -p temp_install/App/Controllers
          mkdir -p temp_install/App/Rules
          mkdir -p temp_install/App/Models
          mkdir -p temp_install/routes
          mkdir -p temp_install/storage/downloads
          mkdir -p temp_install/storage/documentation
          chmod -R 755 temp_install

      - name: Run tests with coverage
        run: |
          php vendor/bin/phpunit --bootstrap dev_build.php --configuration phpunit.xml --no-progress --coverage-html coverage-report --coverage-clover coverage.xml
        env:
          TEMP_ROOT: ${{ github.workspace }}/temp_install/
          DB_DRIVER: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: test_database
          DB_USER: root
          DB_PASSWORD: testpassword

      - name: Deploy coverage to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-report
          publish_branch: gh-pages

  build-and-release:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: phar
          tools: composer:v2
          ini-values: phar.readonly=0

      - name: Generate Version
        id: version
        run: |
          VERSION="v0.$(date +'%y%m%d').${GITHUB_RUN_NUMBER}"
          echo "Generated version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Modify Build Script to Include Version Metadata
        env:
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          sed -i "s/\$phar->setStub(\$stub);/\$phar->setMetadata(['version' => '$VERSION']);\n    \$phar->setStub(\$stub);/" build.php

      - name: Build PHAR
        run: php build.php

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: lucent.phar
          tag_name: ${{ steps.version.outputs.version }}
